# Generated by carnix 0.9.8: carnix generate-nix
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO;
  routinator = crates.crates.routinator."0.4.0" deps;
  __all = [ (routinator {}) ];
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.7";
  };
  deps.arc_swap."0.3.11" = {};
  deps.argon2rs."0.2.5" = {
    blake2_rfc = "0.2.18";
    scoped_threadpool = "0.1.9";
  };
  deps.arrayvec."0.4.10" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.2";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.4" = {};
  deps.backtrace."0.3.26" = {
    backtrace_sys = "0.1.28";
    cfg_if = "0.1.9";
    libc = "0.2.58";
    rustc_demangle = "0.1.15";
    autocfg = "0.1.4";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.58";
    cc = "1.0.37";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.3.1";
    safemem = "0.3.0";
  };
  deps.bcder."0.3.0" = {
    backtrace = "0.3.26";
    bytes = "0.4.12";
    derive_more = "0.14.1";
  };
  deps.bitflags."1.0.4" = {};
  deps.blake2_rfc."0.2.18" = {
    arrayvec = "0.4.10";
    constant_time_eq = "0.1.3";
  };
  deps.byteorder."1.3.1" = {};
  deps.bytes."0.4.12" = {
    byteorder = "1.3.1";
    iovec = "0.1.2";
  };
  deps.cc."1.0.37" = {};
  deps.cfg_if."0.1.9" = {};
  deps.chrono."0.4.6" = {
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    time = "0.1.42";
  };
  deps.clap."2.33.0" = {
    atty = "0.2.11";
    bitflags = "1.0.4";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.4";
  };
  deps.constant_time_eq."0.1.3" = {};
  deps.crossbeam_deque."0.7.1" = {
    crossbeam_epoch = "0.7.1";
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_epoch."0.7.1" = {
    arrayvec = "0.4.10";
    cfg_if = "0.1.9";
    crossbeam_utils = "0.6.5";
    lazy_static = "1.3.0";
    memoffset = "0.2.1";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_queue."0.1.2" = {
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_utils."0.6.5" = {
    cfg_if = "0.1.9";
    lazy_static = "1.3.0";
  };
  deps.daemonize."0.3.0" = {
    libc = "0.2.58";
  };
  deps.derive_more."0.14.1" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
    rustc_version = "0.2.3";
  };
  deps.dirs."2.0.1" = {
    cfg_if = "0.1.9";
    dirs_sys = "0.3.3";
  };
  deps.dirs_sys."0.3.3" = {
    cfg_if = "0.1.9";
    redox_users = "0.3.0";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.encoding_rs."0.8.17" = {
    cfg_if = "0.1.9";
  };
  deps.error_chain."0.11.0" = {
    backtrace = "0.3.26";
  };
  deps.failure."0.1.5" = {
    backtrace = "0.3.26";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
    synstructure = "0.10.2";
  };
  deps.fern."0.5.8" = {
    log = "0.4.6";
  };
  deps.fnv."1.0.6" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.4";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.futures."0.1.27" = {};
  deps.futures_cpupool."0.1.8" = {
    futures = "0.1.27";
    num_cpus = "1.10.0";
  };
  deps.hex."0.3.2" = {};
  deps.httparse."1.3.3" = {};
  deps.iovec."0.1.2" = {
    libc = "0.2.58";
    winapi = "0.2.8";
  };
  deps.json."0.11.13" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.58" = {};
  deps.listenfd."0.3.3" = {
    libc = "0.2.58";
    uuid = "0.6.5";
    winapi = "0.3.7";
  };
  deps.lock_api."0.1.5" = {
    owning_ref = "0.4.0";
    scopeguard = "0.3.3";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.9";
  };
  deps.log_reroute."0.1.2" = {
    arc_swap = "0.3.11";
    log = "0.4.6";
    once_cell = "0.1.8";
  };
  deps.memchr."2.2.0" = {};
  deps.memoffset."0.2.1" = {};
  deps.mio."0.6.19" = {
    iovec = "0.1.2";
    log = "0.4.6";
    net2 = "0.2.33";
    slab = "0.4.2";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.58";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_named_pipes."0.1.6" = {
    log = "0.4.6";
    mio = "0.6.19";
    miow = "0.3.3";
    winapi = "0.3.7";
  };
  deps.mio_uds."0.6.7" = {
    iovec = "0.1.2";
    libc = "0.2.58";
    mio = "0.6.19";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.miow."0.3.3" = {
    socket2 = "0.3.9";
    winapi = "0.3.7";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.9";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.nodrop."0.1.13" = {};
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.8";
    autocfg = "0.1.4";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.4";
  };
  deps.num_cpus."1.10.0" = {
    libc = "0.2.58";
  };
  deps.numtoa."0.1.0" = {};
  deps.once_cell."0.1.8" = {
    parking_lot = "0.7.1";
  };
  deps.owning_ref."0.4.0" = {
    stable_deref_trait = "1.1.1";
  };
  deps.parking_lot."0.7.1" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.4.0";
  };
  deps.parking_lot_core."0.4.0" = {
    rand = "0.6.5";
    smallvec = "0.6.9";
    rustc_version = "0.2.3";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.quick_xml."0.14.0" = {
    derive_more = "0.14.1";
    encoding_rs = "0.8.17";
    failure = "0.1.5";
    log = "0.4.6";
    memchr = "2.2.0";
  };
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.30";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.4";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.4";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.4";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.54";
  };
  deps.redox_users."0.3.0" = {
    argon2rs = "0.2.5";
    failure = "0.1.5";
    rand_os = "0.1.3";
    redox_syscall = "0.1.54";
  };
  deps.remove_dir_all."0.5.1" = {
    winapi = "0.3.7";
  };
  deps.ring."0.13.5" = {
    untrusted = "0.6.2";
    cc = "1.0.37";
    lazy_static = "1.3.0";
    libc = "0.2.58";
  };
  deps.routinator."0.4.0" = {
    bytes = "0.4.12";
    chrono = "0.4.6";
    clap = "2.33.0";
    derive_more = "0.14.1";
    dirs = "2.0.1";
    fern = "0.5.8";
    futures = "0.1.27";
    futures_cpupool = "0.1.8";
    httparse = "1.3.3";
    json = "0.11.13";
    listenfd = "0.3.3";
    log = "0.4.6";
    log_reroute = "0.1.2";
    num_cpus = "1.10.0";
    rpki = "0.4.0";
    slab = "0.4.2";
    tempfile = "3.0.8";
    tokio = "0.1.21";
    tokio_process = "0.2.3";
    toml = "0.4.10";
    unwrap = "1.2.1";
    rustc_version = "0.2.3";
    daemonize = "0.3.0";
    libc = "0.2.58";
    syslog = "4.0.1";
  };
  deps.rpki."0.4.0" = {
    base64 = "0.9.3";
    bcder = "0.3.0";
    bytes = "0.4.12";
    chrono = "0.4.6";
    derive_more = "0.14.1";
    hex = "0.3.2";
    log = "0.4.6";
    quick_xml = "0.14.0";
    ring = "0.13.5";
    serde = "1.0.92";
    untrusted = "0.6.2";
    unwrap = "1.2.1";
    uuid = "0.7.4";
  };
  deps.rustc_demangle."0.1.15" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.safemem."0.3.0" = {};
  deps.scoped_threadpool."0.1.9" = {};
  deps.scopeguard."0.3.3" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.92" = {
    serde_derive = "1.0.92";
  };
  deps.serde_derive."1.0.92" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
  };
  deps.signal_hook."0.1.9" = {
    libc = "0.2.58";
    signal_hook_registry = "1.0.1";
  };
  deps.signal_hook_registry."1.0.1" = {
    arc_swap = "0.3.11";
    libc = "0.2.58";
  };
  deps.slab."0.4.2" = {};
  deps.smallvec."0.6.9" = {};
  deps.socket2."0.3.9" = {
    cfg_if = "0.1.9";
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.stable_deref_trait."1.1.1" = {};
  deps.strsim."0.8.0" = {};
  deps.syn."0.15.34" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.2" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
    unicode_xid = "0.1.0";
  };
  deps.syslog."4.0.1" = {
    error_chain = "0.11.0";
    libc = "0.2.58";
    log = "0.4.6";
    time = "0.1.42";
  };
  deps.tempfile."3.0.8" = {
    cfg_if = "0.1.9";
    rand = "0.6.5";
    remove_dir_all = "0.5.1";
    redox_syscall = "0.1.54";
    libc = "0.2.58";
    winapi = "0.3.7";
  };
  deps.termion."1.5.2" = {
    numtoa = "0.1.0";
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    redox_termios = "0.1.1";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.time."0.1.42" = {
    libc = "0.2.58";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.tokio."0.1.21" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    mio = "0.6.19";
    num_cpus = "1.10.0";
    tokio_codec = "0.1.1";
    tokio_current_thread = "0.1.6";
    tokio_executor = "0.1.7";
    tokio_fs = "0.1.6";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_sync = "0.1.5";
    tokio_tcp = "0.1.3";
    tokio_threadpool = "0.1.14";
    tokio_timer = "0.2.11";
    tokio_trace_core = "0.2.0";
    tokio_udp = "0.1.3";
    tokio_uds = "0.2.5";
  };
  deps.tokio_codec."0.1.1" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    tokio_io = "0.1.12";
  };
  deps.tokio_current_thread."0.1.6" = {
    futures = "0.1.27";
    tokio_executor = "0.1.7";
  };
  deps.tokio_executor."0.1.7" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.27";
  };
  deps.tokio_fs."0.1.6" = {
    futures = "0.1.27";
    tokio_io = "0.1.12";
    tokio_threadpool = "0.1.14";
  };
  deps.tokio_io."0.1.12" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    log = "0.4.6";
  };
  deps.tokio_process."0.2.3" = {
    futures = "0.1.27";
    mio = "0.6.19";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    libc = "0.2.58";
    tokio_signal = "0.2.7";
    mio_named_pipes = "0.1.6";
    winapi = "0.3.7";
  };
  deps.tokio_reactor."0.1.9" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.27";
    lazy_static = "1.3.0";
    log = "0.4.6";
    mio = "0.6.19";
    num_cpus = "1.10.0";
    parking_lot = "0.7.1";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_sync = "0.1.5";
  };
  deps.tokio_signal."0.2.7" = {
    futures = "0.1.27";
    mio = "0.6.19";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    libc = "0.2.58";
    mio_uds = "0.6.7";
    signal_hook = "0.1.9";
    winapi = "0.3.7";
  };
  deps.tokio_sync."0.1.5" = {
    fnv = "1.0.6";
    futures = "0.1.27";
  };
  deps.tokio_tcp."0.1.3" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    iovec = "0.1.2";
    mio = "0.6.19";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.tokio_threadpool."0.1.14" = {
    crossbeam_deque = "0.7.1";
    crossbeam_queue = "0.1.2";
    crossbeam_utils = "0.6.5";
    futures = "0.1.27";
    log = "0.4.6";
    num_cpus = "1.10.0";
    rand = "0.6.5";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
  };
  deps.tokio_timer."0.2.11" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.27";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
  };
  deps.tokio_trace_core."0.2.0" = {
    lazy_static = "1.3.0";
  };
  deps.tokio_udp."0.1.3" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    log = "0.4.6";
    mio = "0.6.19";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.tokio_uds."0.2.5" = {
    bytes = "0.4.12";
    futures = "0.1.27";
    iovec = "0.1.2";
    libc = "0.2.58";
    log = "0.4.6";
    mio = "0.6.19";
    mio_uds = "0.6.7";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.toml."0.4.10" = {
    serde = "1.0.92";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.untrusted."0.6.2" = {};
  deps.unwrap."1.2.1" = {};
  deps.uuid."0.6.5" = {
    cfg_if = "0.1.9";
  };
  deps.uuid."0.7.4" = {};
  deps.vec_map."0.8.1" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
}
